function showDetails(medicationId) {
    const details = {
        med1: {
            "Quais são as principais indicações terapêuticas do RINVOQ?": "Artrite reumatóide ativa moderada a grave em adultos. <br>Artrite psoriática ativa em adultos.<br>Espondilartrite axial, incluindo formas não-radiográficas e espondilite anquilosante ativa.<br>Dermatite atópica moderada a grave em adultos e adolescentes com idade ≥ 12 anos.<br>Colite ulcerosa ativa moderada a grave.<br>Doença de Crohn ativa moderada a grave",
            "Qual é a posologia recomendada para o tratamento da artrite reumatóide com RINVOQ?": "A dose recomendada é de 15 mg uma vez por dia.<br> A descontinuação deve ser considerada em casos sem resposta clínica após 16 semanas",
            "Quais são as contraindicações do uso de RINVOQ?": "O uso é contraindicado em pacientes com:<br>Hipersensibilidade ao princípio ativo ou excipientes.<br>Tuberculose ativa ou outras infecções graves.<br>Compromisso hepático grave.",
            "Quais são as reações adversas mais comuns associadas ao RINVOQ?": "Reações adversas frequentes incluem:<br>Infecções do trato respiratório superior.<br>Aumento da creatina fosfocinase (CPK).<br>Acne, herpes simples, e neutropenia.Náuseas e aumento de enzimas hepáticas (ALT e AST)",
            "Quais cuidados devem ser tomados com pacientes acima de 65 anos ao usar RINVOQ?": "Esses pacientes têm maior risco de eventos adversos, incluindo MACE (eventos cardiovasculares maiores), infecções graves e neoplasias malignas.<br> Deve-se usar a dose mínima eficaz (15 mg por dia) e apenas se alternativas não forem adequadas"
        },
        med2: {
            "Qual é a indicação principal do Ozempic?": "O Ozempic é indicado para o tratamento de adultos com diabetes mellitus tipo 2 insuficientemente controlada, como adjuvante à dieta e ao exercício. Pode ser usado em monoterapia, quando a metformina é inapropriada devido a intolerância ou contraindicações, ou em combinação com outros medicamentos para diabetes",
            "Como deve ser administrado o Ozempic?": "O Ozempic deve ser administrado por via subcutânea no abdómen, coxa ou braço, uma vez por semana, a qualquer hora do dia, com ou sem alimentos. É importante evitar a administração intravenosa ou intramuscular.",
            "Quais são as reações adversas mais comuns associadas ao uso do Ozempic?": "As reações adversas mais frequentes são náuseas, diarreia e vômitos. Estas reações geralmente são leves a moderadas e de curta duração, mas podem levar à interrupção do tratamento em alguns casos.",
            "O Ozempic pode ser usado em pacientes com comprometimento renal ou hepático?": "Sim, o Ozempic pode ser utilizado em pacientes com comprometimento renal ou hepático leve a moderado sem necessidade de ajuste de dose. No entanto, a experiência é limitada em casos graves, sendo necessário cuidado adicional nesses casos",
            "O que fazer em caso de omissão de uma dose?": "Se uma dose for omitida, ela deve ser administrada o mais rapidamente possível dentro de um prazo de 5 dias. Caso tenham passado mais de 5 dias, a dose omitida deve ser ignorada e o paciente deve retomar a posologia normal no dia previamente estabelecido.",

        },
        med3: {
            "Quais são as indicações terapêuticas do Paclitaxel Accord?": "Carcinoma do ovário (primeira e segunda linha de tratamento).<br>Carcinoma da mama (adjuvante, localmente avançado ou metastático).<br>Carcinoma avançado de células não pequenas do pulmão.<br>Sarcoma de Kaposi relacionado com SIDA, resistente a antraciclinas lipossómicas.<br>", 
            "Quais os cuidados especiais na administração do Paclitaxel Accord?": "Deve ser administrado em unidades especializadas sob supervisão de um oncologista qualificado. É necessária pré-medicação com corticosteroides, anti-histamínicos e antagonistas dos recetores H2 para prevenir reações de hipersensibilidade. A administração deve ser feita através de um filtro com membrana microporosa ≤ 0,22 µm.",
             "Quais são os principais efeitos adversos associados ao uso de Paclitaxel?": "Efeitos comuns incluem:<br>Mielossupressão (neutropenia, anemia, trombocitopenia).<br>Neuropatia periférica.<br>Reações de hipersensibilidade.<br>Artralgias/mialgias.<br>Alopécia.<br>Em casos raros, reações graves como anafilaxia e colite pseudomembranosa.<br>", 
             "Como deve ser armazenado e manuseado o Paclitaxel Accord?": "<b>Armazenamento</b>: Não conservar acima de 25°C e proteger da luz. Após diluição, usar em até 24 horas a 2-8°C (condições assépticas controladas permitem maior flexibilidade).<br><b>Manuseio:</b> Deve ser diluído em condições assépticas por pessoal treinado. É necessário uso de luvas e evitar contato com pele ou mucosas.", 
            "Quais são as contra-indicações para o uso de Paclitaxel Accord?": "Hipersensibilidade ao Paclitaxel ou excipientes (especialmente óleo de rícino polioxietilado 35).<br>Neutropenia grave antes do início do tratamento (<1.500/mm³ para tumores sólidos e <1.000/mm³ no sarcoma de Kaposi).<br>Durante a amamentação.<br>Em casos de infecções graves e não controladas no sarcoma de Kaposi."
        },
        med4: {
            "Quais são as indicações terapêuticas do Diovan 80 mg?": "Tratamento da hipertensão arterial essencial em adultos e em crianças/adolescentes de 6 a menos de 18 anos.<br>Tratamento de insuficiência cardíaca sintomática em adultos quando os inibidores da enzima de conversão da angiotensina (ECA) não são tolerados.<br>Terapia após enfarte do miocárdio recente em adultos clinicamente estáveis (12 horas a 10 dias).",
            "Quais são as contraindicações principais?": "Hipersensibilidade à substância ativa ou a qualquer excipiente.<br>Compromisso hepático grave, cirrose biliar e colestase.<br>Gravidez no segundo e terceiro trimestres.<br>Uso concomitante com medicamentos contendo aliscireno em pacientes com diabetes mellitus ou função renal comprometida (TFG <60 ml/min/1,73m²).",
            "Quais são os efeitos adversos mais comuns relatados?": "Os efeitos adversos mais frequentes incluem:<br>Tontura.<br>Hipotensão.<br>Dor abdominal.<br>Fadiga.<br>Em casos menos frequentes, pode ocorrer hipercaliemia e insuficiência renal.<br>",
            "Qual a posologia recomendada para hipertensão em adultos?": "A dose inicial recomendada é de 80 mg uma vez ao dia. Caso a pressão arterial não seja devidamente controlada, a dose pode ser aumentada para 160 mg e, se necessário, até o máximo de 320 mg por dia. Diovan pode ser administrado com outros agentes anti-hipertensores.<br>",
            "Quais cuidados especiais devem ser observados na administração do medicamento?": "Monitorização de potássio: Especialmente ao usar diuréticos poupadores de potássio ou substitutos de sal contendo potássio.<br>Função renal: Recomenda-se cuidado em pacientes com função renal comprometida (depuração de creatinina <10 ml/min).<br>Gravidez: Deve ser interrompido imediatamente se diagnosticada a gravidez.<br>Hepatopatias: A dose não deve exceder 80 mg em pacientes com comprometimento hepático leve a moderado sem colestase.<br>"
        },
        med5: {
            "Para quem o Influvac Tetra é indicado?": "É indicado para a profilaxia da gripe em adultos e crianças a partir de 6 meses de idade, especialmente para aqueles com maior risco de complicações associadas à gripe.<br>",
            "Quais são os componentes ativos da vacina?": "Contém antigénios de superfície do vírus Influenza (hemaglutinina e neuraminidase) das estirpes:<br>A/Victoria/4897/2022 (H1N1)pdm09<br>A/Darwin/9/2021 (H3N2)<br>B/Austria/1359417/2021<br>B/Phuket/3073/2013.",
            "Quais são as contraindicações do Influvac Tetra?": "É contraindicado para pessoas com hipersensibilidade às substâncias ativas, a qualquer excipiente mencionado ou a componentes como ovos, formaldeído, brometo de cetiltrimetilamónio, polissorbato 80 ou gentamicina. Também não deve ser administrado em doentes com febre ou infeções agudas.",
            "Como deve ser administrado o Influvac Tetra?": "A vacina deve ser administrada por via intramuscular ou subcutânea profunda. Em crianças menores de 35 meses, a injeção é preferencialmente no lado antero-lateral da coxa, enquanto em crianças acima de 36 meses e adultos, no músculo deltoide.<br>",
            "Quais são os possíveis efeitos adversos mais comuns?": "Os efeitos adversos mais frequentes incluem dor no local da injeção, fadiga, cefaleia, e em crianças pequenas, sonolência, irritabilidade e perda de apetite. Em geral, essas reações são leves e desaparecem espontaneamente dentro de 1 a 3 dias."
        },
        med6: {
            "Para quem está indicado o Comirnaty?": "O Comirnaty está indicado para imunização ativa para prevenir a COVID-19 causada pelo SARS-CoV-2 em indivíduos com idade igual ou superior a 12 anos. A utilização segue as recomendações oficiais.<br>",
            "Quais as principais contraindicações?": "A vacina é contraindicada em casos de hipersensibilidade à substância ativa ou a qualquer um dos excipientes mencionados na secção 6.1 do documento",
            "Quais os efeitos adversos mais frequentes observados?": "Os efeitos adversos mais comuns incluem dor no local da injeção (>80%), fadiga (>60%), cefaleias (>50%), mialgia (>40%), arrepios (>30%), artralgia (>20%) e febre (>10%). Estes são geralmente leves ou moderados e resolvem-se em alguns dias.<br>",
            "Existe algum risco associado à vacinação em pessoas jovens?": "Sim, há um risco aumentado de miocardite e pericardite, especialmente em jovens do sexo masculino, geralmente observados dentro de 14 dias após a vacinação.<br>",
            "Como deve ser administrada a vacina?": "O Comirnaty deve ser administrado por via intramuscular, preferencialmente no músculo deltoide do braço. A vacina não deve ser diluída antes do uso e não pode ser misturada com outros medicamentos na mesma seringa.<br>"
        },

        med7: {
            "Qual é a substância ativa do medicamento Triticum e para que é indicado?": "A substância ativa é o cloridrato de trazodona, e o medicamento é indicado para o tratamento da depressão",
            "Quais as contraindicações principais do uso de Triticum?": "O Triticum é contraindicado para:<br>Indivíduos com hipersensibilidade à substância ativa ou a qualquer excipiente.<br>Menores de 18 anos.<br>Pacientes em recuperação de enfarte agudo do miocárdio.<br>Indivíduos com intoxicação por álcool ou hipnóticos.",
            "Como deve ser administrado e qual é a dosagem recomendada?": "A dose recomendada é de 1-2 comprimidos, duas a três vezes por dia, preferencialmente após as refeições, ajustada pelo médico de acordo com a gravidade da doença, peso, idade e estado geral do paciente. Para idosos ou pacientes frágeis, a dose inicial recomendada é de 100 mg/dia, administrada em doses fracionadas ou numa única dose à noite, podendo ser aumentada conforme a tolerância e eficácia.<br>",
            "Quais são os efeitos adversos mais comuns do Triticum?": "Os efeitos adversos incluem:<br>Sonolência, tontura, náusea, boca seca e dores de cabeça.<br>Em casos graves, podem ocorrer ideação suicida, priapismo, síndrome serotoninérgica e hipotensão ortostática.<br>",
            "Há restrições no uso de Triticum durante a gravidez ou amamentação?": "Durante a gravidez, deve-se ter precaução ao prescrever Triticum. Quando usado até o momento do parto, é recomendada a monitorização dos recém-nascidos para sintomas de abstinência. Na amamentação, como os dados sobre excreção no leite humano são limitados, a decisão deve considerar os benefícios para a mãe e o bebê."
        },
        med8: {
            "Quais são as principais indicações terapêuticas do Depakine Xarope 40 mg/ml?": "Tratamento de crises epiléticas generalizadas ou parciais, incluindo convulsões clónicas, tónicas, tónico-clónicas, mioclónicas e ausências.<br>Tratamento de formas mistas de epilepsia, incluindo as síndromes de West e Lennox-Gastaut.<br>Tratamento de episódios maníacos associados a perturbações bipolares, especialmente quando o lítio está contraindicado ou não é tolerado.",
            "Quais são os principais efeitos adversos associados ao uso do Depakine?": "Os efeitos adversos incluem:<br>Muito frequentes: Tremores, náuseas.<br>Frequentes: Trombocitopenia, sonolência, aumento de peso, hiponatremia.<br>Pouco frequentes: Pancreatite, hipotermia, hiperamonemia associada a sintomas neurológicos.<br>Raros: Hepatite grave, encefalopatia, rabdomiólise.<br>",
            "Quais as contraindicações principais para o uso de Depakine?": "O Depakine está contraindicado em casos de:<br>Hepatite aguda ou crónica.<br>História pessoal ou familiar de hepatite grave.<br>Doenças mitocondriais causadas por mutações no gene POLG.<br>Tratamento de epilepsia e perturbação bipolar em mulheres grávidas, salvo se não houver alternativa eficaz.<br>",
            "Quais são as precauções específicas para mulheres em idade fértil ou grávidas?": "O Depakine tem elevado risco teratogénico. É contraindicado durante a gravidez, exceto em casos sem alternativas.<br>As mulheres em idade fértil devem aderir ao Programa de Prevenção da Gravidez, usando contraceção eficaz.<br>Em caso de gravidez, o tratamento deve ser reavaliado e alternativas devem ser consideradas.<br>",
            "Como é feita a administração inicial e o ajuste de dose do Depakine?": "Para epilepsia:<br>Início: 10-15 mg/kg/dia, aumentando gradualmente até 20-30 mg/kg/dia.<br>Doses superiores a 50 mg/kg/dia exigem vigilância rigorosa.<br>Para perturbação bipolar:<br>Adultos: Dose inicial de 750 mg/dia, podendo ser ajustada até 1000-2000 mg/dia com base na resposta clínica.<br>"
        },
        med9: {
            "Quais são as principais indicações terapêuticas da Lenalidomida Tecnigen?": "Mieloma múltiplo:<br>Tratamento de manutenção em pacientes adultos recém-diagnosticados após transplante autólogo de células-tronco.<br>Em combinação com outros medicamentos (dexametasona, bortezomibe ou melfalano e prednisona) para pacientes inelegíveis ao transplante ou que já receberam pelo menos um tratamento anterior.<br>Linfoma folicular: Em combinação com rituximabe, para pacientes adultos previamente tratados.",
            "Quais são os ajustes de dose recomendados para trombocitopenia ou neutropenia?": "Trombocitopenia:<br>Interromper o tratamento quando as plaquetas caírem para níveis críticos (ex.: < 25 x 10⁹/L).<br>Retomar em níveis ajustados ao recuperar valores aceitáveis.<br>Neutropenia:<br>Interromper o tratamento quando a contagem de neutrófilos cair abaixo de 0,5 x 10⁹/L.<br>Considerar fatores de crescimento e retomar a dose reduzida quando os valores recuperarem.<br>",
            "Quais são as principais contraindicações?": "Hipersensibilidade à lenalidomida ou aos excipientes.<br>Gravidez devido ao alto risco de teratogenicidade.<br>Mulheres com potencial para engravidar, salvo sob rígidas condições do Programa de Prevenção da Gravidez.<br>",
            "Quais precauções são recomendadas para evitar a teratogenicidade?": "Mulheres em idade fértil devem usar métodos contraceptivos eficazes pelo menos 4 semanas antes de iniciar o tratamento e até 4 semanas após o término.<br>Testes de gravidez regulares (mensais) supervisionados por um médico são mandatórios.<br>Homens tratados com lenalidomida devem usar preservativos durante relações sexuais para prevenir exposição ao feto, mesmo após vasectomia.<br>",
            "Como deve ser administrado o medicamento?": "Via oral, no mesmo horário diariamente, com ou sem alimentos.<br>As cápsulas devem ser ingeridas inteiras, sem serem abertas, partidas ou mastigadas.<br>Recomenda-se cuidado ao retirar a cápsula do blister para evitar danos.<br>"
        },
        med10: {
            "Quais são as principais indicações terapêuticas do Ciplox?": "O Ciplox está indicado para o tratamento de várias infeções bacterianas, incluindo:<br>Infeções respiratórias (pneumonia, bronquites, exacerbações da doença pulmonar obstrutiva crónica).<br>Infeções do trato urinário (cistite, pielonefrite, prostatite bacteriana).<br>Doenças de transmissão sexual, como uretrite e cervicite gonocócica.<br>Infeções gastrointestinais (ex.: diarreia do viajante).<br>Antraz por inalação.<br>Deve-se consultar o médico antes de iniciar o tratamento, especialmente em casos de resistência bacteriana.",
            "Quais são os efeitos adversos mais comuns associados ao Ciplox?": "Os efeitos adversos mais comuns incluem:<br>Náuseas.<br>Diarreia.<br>Dor abdominal.<br>Tonturas.<br>Em casos raros, podem ocorrer reações alérgicas graves, alterações no sistema nervoso central (como convulsões), ou problemas musculosqueléticos, como tendinite e rutura de tendão.<br>",
            "Como deve ser administrado o Ciplox?": "O Ciplox deve ser ingerido com líquido, sem mastigar. Pode ser tomado independentemente das refeições, mas sua absorção é mais rápida com o estômago vazio. Evite tomá-lo com produtos lácteos ou sucos enriquecidos com minerais, pois podem interferir na sua eficácia.<br>",
            "Quais são as contraindicações do uso do Ciplox?": "O Ciplox não deve ser usado em casos de:<br>Hipersensibilidade à ciprofloxacina ou outras quinolonas.<br>Uso concomitante de tizanidina.<br>Histórico de reações adversas graves às fluoroquinolonas, como tendinite ou neuropatia.<br>",
            "O Ciplox é seguro para uso em crianças e grávidas?": "Crianças: Pode ser utilizado em casos específicos, como infeções graves, mas requer avaliação cuidadosa devido ao risco de artropatia.<br>Grávidas: Embora não haja evidências claras de malformações, recomenda-se evitar o uso durante a gravidez devido ao potencial risco de danos à cartilagem do feto.<br>Amamentação: Não deve ser usado, pois a ciprofloxacina é excretada no leite materno.<br>"
        }
    };

    const detailElement = document.getElementById("medication-details");
    if (details[medicationId]) {
        const med = details[medicationId];
        let content = "";

        for (const key in med) {
            content += `<p><strong>${key}</strong><br> ${med[key] || "N/A"}</p>`;
        }

        detailElement.innerHTML = content;
    } else {
        detailElement.innerHTML = `<p>No details available for this medication.</p>`;
    }
}
